### PR TITLE
Upgrade to 'argcomplete v1.9.3'

### PR DESCRIPTION
**Pull request by ashahba**

### CODE REVIEW

**Comment by ashahba** [comment]
I think I have it right this time.
Once you merge this, I grab the hash and update `ncloud`.
By the way now you see your changes so we can bring them into our main branch so that in the future we don't forget what we did 🙁

**Comment by ashahba** [comment]
I also tested this with `ncloud` and it works like a charm.

**Comment by ashahba** [comment]
```
(.venv) ashahba@ashahba1113-api-0:~/ashahba-api-0/source_code/ncloud$ ncloud model 
d               -h              i               l               ls              res             s               stop            --table-format  
deploy          --help          import          list            r               results         show            t               train           

```

**Comment by ashahba** [comment]
Tests also passed here: https://github.com/NervanaSystems/ncloud/pull/327

**Review by IcarusMJ12 — APPROVED** [review]

**Pull request merged**
